export const WAREHOUSE_NAV_PERMISSIONS = {
    orders: ["orders:read"],
    serviceRequests: ["orders:read"],
    pricingReview: ["pricing:review", "pricing:approve_standard", "pricing:adjust"],
    scanning: ["scanning:scan_out", "scanning:scan_in"],
    conditions: [
        "conditions:view_history",
        "conditions:update",
        "conditions:view_items_needing_attention",
    ],
    eventCalendar: ["orders:read"],
    companies: ["companies:read"],
    warehouses: ["warehouses:read"],
    zones: ["zones:read", "zones:create", "zones:update", "zones:delete"],
    brands: ["brands:read"],
    assets: ["assets:read"],
    collections: ["collections:read"],
    inboundRequest: ["orders:read"],
    resetPassword: ["auth:reset_password"],
} as const;

export const WAREHOUSE_ACTION_PERMISSIONS = {
    ordersRead: "orders:read",
    ordersUpdate: "orders:update",
    ordersExport: "orders:export",
    ordersAddJobNumber: "orders:add_job_number",
    ordersAddTimeWindows: "orders:add_time_windows",
    ordersCancel: "orders:cancel",
    ordersSubmitForApproval: "pricing:review",
    ordersPricingAdjust: "pricing:adjust",
    ordersDownloadGoodsForm: "orders:read",
    companiesCreate: "companies:create",
    companiesUpdate: "companies:update",
    companiesArchive: "companies:archive",
    warehousesCreate: "warehouses:create",
    warehousesUpdate: "warehouses:update",
    warehousesArchive: "warehouses:archive",
    zonesCreate: "zones:create",
    zonesUpdate: "zones:update",
    zonesDelete: "zones:delete",
    assetsCreate: "assets:create",
    assetsRead: "assets:read",
    assetsUpdate: "assets:update",
    assetsDelete: "assets:delete",
    assetsBulkUpload: "assets:bulk_upload",
    collectionsCreate: "collections:create",
    collectionsRead: "collections:read",
    collectionsUpdate: "collections:update",
    collectionsDelete: "collections:delete",
} as const;
